# Generated by Django 6.0.5 on 2026-05-08 04:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_organization_account_owner_organization_address_and_more'),
        ('tickets', '0002_alter_ticketcomment_visibility'),
        ('workspaces', '0002_workspace_first_response_target_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('address', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('disabled', 'Disabled'), ('stubbed', 'Stubbed'), ('ready', 'Ready for provider')], default='stubbed', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('provider_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_channels', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=20)),
                ('status', models.CharField(choices=[('stubbed', 'Stubbed'), ('queued', 'Queued'), ('processed', 'Processed'), ('failed', 'Failed')], default='stubbed', max_length=20)),
                ('message_id', models.CharField(max_length=255)),
                ('sender', models.EmailField(max_length=254)),
                ('recipients', models.JSONField(default=list)),
                ('subject', models.CharField(max_length=255)),
                ('text_body', models.TextField(blank=True)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_messages', to='tickets.ticketcomment')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_messages', to='crm.contact')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_messages', to='crm.organization')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_messages', to='tickets.ticket')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='workspaces.workspace')),
                ('mailbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='communications.mailboxchannel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailIngestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('stubbed', 'Stubbed'), ('processed', 'Processed'), ('duplicate', 'Duplicate'), ('failed', 'Failed')], default='stubbed', max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_ingest_logs', to='workspaces.workspace')),
                ('email_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingest_logs', to='communications.emailmessage')),
                ('mailbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingest_logs', to='communications.mailboxchannel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailDeliveryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('stubbed', 'Stubbed'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='stubbed', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('response', models.TextField(blank=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_delivery_attempts', to='workspaces.workspace')),
                ('email_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='communications.emailmessage')),
            ],
            options={
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='communicati_workspa_28d528_idx'), models.Index(fields=['workspace', 'attempted_at'], name='communicati_workspa_b9d82b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mailboxchannel',
            index=models.Index(fields=['workspace', 'status'], name='communicati_workspa_1799fb_idx'),
        ),
        migrations.AddIndex(
            model_name='mailboxchannel',
            index=models.Index(fields=['workspace', 'address'], name='communicati_workspa_41da56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mailboxchannel',
            unique_together={('workspace', 'address')},
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['workspace', 'direction', 'status'], name='communicati_workspa_6874d6_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['workspace', 'ticket'], name='communicati_workspa_64148c_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['workspace', 'message_id'], name='communicati_workspa_ab8f3c_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['workspace', 'processed_at'], name='communicati_workspa_f48fa9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailmessage',
            unique_together={('workspace', 'message_id')},
        ),
        migrations.AddIndex(
            model_name='emailingestlog',
            index=models.Index(fields=['workspace', 'status'], name='communicati_workspa_d5b266_idx'),
        ),
        migrations.AddIndex(
            model_name='emailingestlog',
            index=models.Index(fields=['workspace', 'message_id'], name='communicati_workspa_9d3bfd_idx'),
        ),
    ]
