# Generated by Django 6.0.5 on 2026-05-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_emailattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxchannel',
            name='encrypted_imap_password',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mailboxchannel',
            name='encrypted_smtp_password',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mailboxchannel',
            name='imap_folder',
            field=models.CharField(default='INBOX', max_length=120),
        ),
        migrations.AddField(
            model_name='mailboxchannel',
            name='imap_host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mailboxchannel',
            name='imap_last_uid',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='mailboxchannel',
            name='imap_port',
            field=models.PositiveIntegerField(default=993),
        ),
        migrations.AddField(
            model_name='mailboxchannel',
            name='imap_use_ssl',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mailboxchannel',
            name='imap_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mailboxchannel',
            name='inbound_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mailboxchannel',
            name='outbound_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mailboxchannel',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mailboxchannel',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='mailboxchannel',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mailboxchannel',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mailboxchannel',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
