# Generated by Django 6.0.5 on 2026-05-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='first_response_target_minutes',
            field=models.PositiveIntegerField(default=240),
        ),
        migrations.AddField(
            model_name='workspace',
            name='next_response_target_minutes',
            field=models.PositiveIntegerField(default=480),
        ),
        migrations.AddField(
            model_name='workspace',
            name='resolution_target_minutes',
            field=models.PositiveIntegerField(default=4320),
        ),
    ]
