# Generated by Django 6.0.5 on 2026-05-08 05:11

import datetime
import django.db.models.deletion
import secrets
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_crmimportjob_crmimportrow_and_more'),
        ('workspaces', '0002_workspace_first_response_target_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHoursCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='UTC', max_length=80)),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('starts_at', models.TimeField(default=datetime.time(9, 0))),
                ('ends_at', models.TimeField(default=datetime.time(17, 0))),
                ('closed_dates', models.JSONField(blank=True, default=list)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_calendar', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('invite_type', models.CharField(choices=[('internal', 'Internal user'), ('customer', 'Customer user')], max_length=20)),
                ('role', models.CharField(blank=True, choices=[('owner', 'Owner'), ('admin', 'Admin'), ('agent', 'Agent'), ('viewer', 'Viewer')], max_length=20)),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=160, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_workspace_invitations', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='crm.contact')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_workspace_invitations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='crm.organization')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'invite_type'], name='workspaces__workspa_441f67_idx'), models.Index(fields=['token'], name='workspaces__token_4bc303_idx'), models.Index(fields=['workspace', 'email'], name='workspaces__workspa_f56ea8_idx')],
            },
        ),
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], max_length=20)),
                ('first_response_target_minutes', models.PositiveIntegerField(default=240)),
                ('next_response_target_minutes', models.PositiveIntegerField(default=480)),
                ('resolution_target_minutes', models.PositiveIntegerField(default=4320)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_policies', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'priority'], name='workspaces__workspa_730a9a_idx')],
                'unique_together': {('workspace', 'priority')},
            },
        ),
    ]
