# Generated by Django 6.0.5 on 2026-05-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_applicationstoragesettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationStorageSettings',
        ),
    ]
