# Generated by Django 6.0.5 on 2026-05-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_delete_applicationstoragesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='theme_custom_tokens',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workspace',
            name='theme_preset',
            field=models.CharField(choices=[('threadline_light', 'Threadline Light'), ('github_dark', 'GitHub Dark'), ('catppuccin_mocha', 'Catppuccin Mocha'), ('nord', 'Nord'), ('solarized_light', 'Solarized Light'), ('dracula', 'Dracula'), ('high_contrast', 'High Contrast')], default='threadline_light', max_length=40),
        ),
    ]
