# Generated by Django 6.0.5 on 2026-05-08 02:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('tickets', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('billable', models.BooleanField(default=False)),
                ('customer_visible', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='crm.contact')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='crm.organization')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='tickets.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['workspace', 'user', 'started_at'], name='time_tracki_workspa_4261b6_idx'), models.Index(fields=['workspace', 'ticket'], name='time_tracki_workspa_5a7028_idx'), models.Index(fields=['workspace', 'organization'], name='time_tracki_workspa_cef6ac_idx'), models.Index(fields=['workspace', 'contact'], name='time_tracki_workspa_32afd9_idx'), models.Index(fields=['workspace', 'customer_visible'], name='time_tracki_workspa_2012b1_idx')],
            },
        ),
    ]
