# Generated by Django 6.0.5 on 2026-05-08 03:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('tickets', '0001_initial'),
        ('time_tracking', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTimer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('billable', models.BooleanField(default=True)),
                ('customer_visible', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_timers', to='crm.contact')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_timers', to='crm.organization')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_timers', to='tickets.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_timers', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_timers', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'user'], name='time_tracki_workspa_8274b9_idx'), models.Index(fields=['workspace', 'ticket'], name='time_tracki_workspa_4b0116_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'user'), name='one_active_timer_per_workspace_user')],
            },
        ),
    ]
