# Generated by Django 6.0.5 on 2026-05-08 05:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('crm', '0002_organization_account_owner_organization_address_and_more'),
        ('tickets', '0003_ticket_first_response_due_at_and_more'),
        ('workspaces', '0002_workspace_first_response_target_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['workspace', 'event_type'], name='activity_ac_workspa_906b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['workspace', 'actor'], name='activity_ac_workspa_af76af_idx'),
        ),
    ]
