# Generated by Django 6.0.5 on 2026-05-08 02:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=220)),
                ('domain', models.CharField(blank=True, max_length=180)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=220)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='workspaces.workspace')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['workspace', 'name'], name='crm_organiz_workspa_245ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['workspace', 'created_at'], name='crm_organiz_workspa_360023_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['workspace', 'organization'], name='crm_contact_workspa_cb5614_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['workspace', 'email'], name='crm_contact_workspa_7e3645_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('workspace', 'email')},
        ),
    ]
