# Generated by Django 6.0.5 on 2026-05-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='account_owner',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='annual_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='employee_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='health_score',
            field=models.PositiveSmallIntegerField(default=80),
        ),
        migrations.AddField(
            model_name='organization',
            name='industry',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='organization',
            name='renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('prospect', 'Prospect'), ('at_risk', 'At risk'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='tier',
            field=models.CharField(choices=[('standard', 'Standard'), ('priority', 'Priority'), ('enterprise', 'Enterprise')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['workspace', 'status'], name='crm_organiz_workspa_c2971b_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['workspace', 'tier'], name='crm_organiz_workspa_19f654_idx'),
        ),
    ]
