# Generated by Django 6.0.5 on 2026-05-08 05:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_organization_account_owner_organization_address_and_more'),
        ('workspaces', '0002_workspace_first_response_target_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('import_type', models.CharField(choices=[('organizations', 'Organizations'), ('contacts', 'Contacts')], max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('preview', 'Preview'), ('imported', 'Imported'), ('failed', 'Failed')], default='preview', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_import_jobs', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CRMImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('data', models.JSONField(default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_object_id', models.UUIDField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='crm.crmimportjob')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.AddIndex(
            model_name='crmimportjob',
            index=models.Index(fields=['workspace', 'status'], name='crm_crmimpo_workspa_c989b3_idx'),
        ),
        migrations.AddIndex(
            model_name='crmimportjob',
            index=models.Index(fields=['workspace', 'import_type'], name='crm_crmimpo_workspa_d58fe7_idx'),
        ),
    ]
