# Generated by Django 6.0.5 on 2026-05-08 05:11

import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0003_businesshourscalendar_invitation_slapolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('ticket', 'Ticket'), ('comment', 'Comment'), ('organization', 'Organization'), ('contact', 'Contact')], max_length=40)),
                ('object_id', models.UUIDField()),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('customer_visible', models.BooleanField(default=False)),
                ('organization_id', models.UUIDField(blank=True, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_documents', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'entity_type'], name='search_sear_workspa_848260_idx'), models.Index(fields=['workspace', 'organization_id', 'customer_visible'], name='search_sear_workspa_1e2105_idx')],
                'unique_together': {('workspace', 'entity_type', 'object_id')},
            },
        ),
    ]
