# Generated by Django 6.0.5 on 2026-05-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchdocument',
            name='entity_type',
            field=models.CharField(choices=[('ticket', 'Ticket'), ('comment', 'Comment'), ('organization', 'Organization'), ('contact', 'Contact'), ('solution_snippet', 'Solution snippet')], max_length=40),
        ),
    ]
