# Generated by Django 6.0.5 on 2026-05-28 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_crmimportrow_duplicate_resolution'),
        ('search', '0002_alter_searchdocument_entity_type'),
        ('workspaces', '0005_delete_applicationstoragesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdocument',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.contact'),
        ),
        migrations.AddIndex(
            model_name='searchdocument',
            index=models.Index(fields=['workspace', 'organization_id', 'contact', 'customer_visible'], name='search_sear_workspa_536c72_idx'),
        ),
    ]
