# Generated by Django 6.0.5 on 2026-05-09 14:11

from django.db import migrations, models


def encrypt_existing_keys(apps, schema_editor):
    from ai.crypto import encrypt_secret

    AIProviderSettings = apps.get_model("ai", "AIProviderSettings")
    for settings in AIProviderSettings.objects.exclude(api_key=""):
        settings.encrypted_api_key = encrypt_secret(settings.api_key)
        settings.api_key = ""
        settings.save(update_fields=["encrypted_api_key", "api_key"])


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovidersettings',
            name='encrypted_api_key',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(encrypt_existing_keys, migrations.RunPython.noop),
    ]
