# Generated by Django 6.0.5 on 2026-05-09 14:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aiprovidersettings_encrypted_api_key'),
        ('crm', '0004_crmimportrow_duplicate_resolution'),
        ('tickets', '0004_savedticketfilter_ticketrelation_and_more'),
        ('time_tracking', '0002_activetimer'),
        ('workspaces', '0004_applicationstoragesettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovidersettings',
            name='crm_insights_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='digest_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='ticket_drafts_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='time_suggestions_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticketaianalysis',
            name='customer_reply_draft',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticketaianalysis',
            name='escalation_risk',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ticketaianalysis',
            name='feedback',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='ticketaianalysis',
            name='internal_note_draft',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticketaianalysis',
            name='missing_info',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ticketaianalysis',
            name='next_actions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ticketaianalysis',
            name='root_cause_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticketaianalysis',
            name='suggested_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='AIRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow', models.CharField(choices=[('ticket_workbench', 'Ticket workbench'), ('crm_insight', 'CRM insight'), ('time_suggestion', 'Time suggestion'), ('workspace_digest', 'Workspace digest'), ('solution_memory', 'Solution memory')], max_length=40)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('subject_type', models.CharField(blank=True, max_length=40)),
                ('subject_id', models.UUIDField(blank=True, null=True)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('context_refs', models.JSONField(blank=True, default=list)),
                ('selected_actions', models.JSONField(blank=True, default=list)),
                ('rejected_actions', models.JSONField(blank=True, default=list)),
                ('feedback', models.CharField(blank=True, max_length=40)),
                ('raw_model', models.CharField(blank=True, max_length=160)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('privacy_mode', models.CharField(default='zdr', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_runs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_runs', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AISuggestedAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=180)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_ai_actions', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_actions', to='ai.airun')),
                ('ticket_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_actions', to='ai.ticketaianalysis')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggested_actions', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CRMInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField()),
                ('recurring_issues', models.JSONField(blank=True, default=list)),
                ('product_areas', models.JSONField(blank=True, default=list)),
                ('risks', models.JSONField(blank=True, default=list)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='crm.contact')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='crm.organization')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_insights', to='ai.airun')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_insights', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SolutionSnippet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solution_snippets', to='ai.airun')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_snippets', to='tickets.ticket')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_snippets', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketReplyDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audience', models.CharField(choices=[('customer', 'Customer'), ('internal', 'Internal')], max_length=20)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_drafts', to='ai.ticketaianalysis')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_reply_drafts', to='ai.airun')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reply_drafts', to='tickets.ticket')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_reply_drafts', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntrySuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggested_minutes', models.PositiveIntegerField(default=15)),
                ('billable', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_time_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='time_tracking.timeentry')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_suggestions', to='ai.airun')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_time_suggestions', to='tickets.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_time_suggestions', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entry_suggestions', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceDigest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('summary', models.TextField()),
                ('themes', models.JSONField(blank=True, default=list)),
                ('accounts_at_risk', models.JSONField(blank=True, default=list)),
                ('time_insights', models.JSONField(blank=True, default=list)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_digests', to='ai.airun')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_digests', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.AddIndex(
            model_name='airun',
            index=models.Index(fields=['workspace', 'workflow', 'created_at'], name='ai_airun_workspa_3964ee_idx'),
        ),
        migrations.AddIndex(
            model_name='airun',
            index=models.Index(fields=['workspace', 'status'], name='ai_airun_workspa_e397d6_idx'),
        ),
        migrations.AddIndex(
            model_name='airun',
            index=models.Index(fields=['workspace', 'subject_type', 'subject_id'], name='ai_airun_workspa_18fa84_idx'),
        ),
        migrations.AddIndex(
            model_name='aisuggestedaction',
            index=models.Index(fields=['workspace', 'status'], name='ai_aisugges_workspa_a3e619_idx'),
        ),
        migrations.AddIndex(
            model_name='aisuggestedaction',
            index=models.Index(fields=['workspace', 'action_type'], name='ai_aisugges_workspa_edfb2f_idx'),
        ),
        migrations.AddIndex(
            model_name='crminsight',
            index=models.Index(fields=['workspace', 'organization', 'created_at'], name='ai_crminsig_workspa_7cde48_idx'),
        ),
        migrations.AddIndex(
            model_name='crminsight',
            index=models.Index(fields=['workspace', 'contact', 'created_at'], name='ai_crminsig_workspa_c90380_idx'),
        ),
        migrations.AddIndex(
            model_name='solutionsnippet',
            index=models.Index(fields=['workspace', 'approved'], name='ai_solution_workspa_6c0fe6_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketreplydraft',
            index=models.Index(fields=['workspace', 'ticket', 'status'], name='ai_ticketre_workspa_28093e_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentrysuggestion',
            index=models.Index(fields=['workspace', 'ticket', 'status'], name='ai_timeentr_workspa_8e70ab_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentrysuggestion',
            index=models.Index(fields=['workspace', 'user', 'status'], name='ai_timeentr_workspa_2992dd_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacedigest',
            index=models.Index(fields=['workspace', 'period_end'], name='ai_workspac_workspa_a46de6_idx'),
        ),
    ]
