# Generated by Django 6.0.5 on 2026-05-09 15:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_aiprovidersettings_crm_insights_enabled_and_more'),
        ('workspaces', '0004_applicationstoragesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovidersettings',
            name='queue_intelligence_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='reply_composer_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='solution_memory_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='airun',
            name='latency_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airun',
            name='provider_generation_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='crminsight',
            name='hygiene_suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='crminsight',
            name='recommended_next_touch',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crminsight',
            name='support_tone',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='ticketaianalysis',
            name='customer_sentiment',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='ticketaianalysis',
            name='next_best_action',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticketaianalysis',
            name='similar_tickets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ticketaianalysis',
            name='urgency_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticketreplydraft',
            name='prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='timeentrysuggestion',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='airun',
            name='workflow',
            field=models.CharField(choices=[('ticket_workbench', 'Ticket workbench'), ('reply_composer', 'Reply composer'), ('crm_insight', 'CRM insight'), ('time_suggestion', 'Time suggestion'), ('workspace_digest', 'Workspace digest'), ('solution_memory', 'Solution memory'), ('queue_intelligence', 'Queue intelligence')], max_length=40),
        ),
        migrations.CreateModel(
            name='QueueIntelligenceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('likely_urgent', models.JSONField(blank=True, default=list)),
                ('stale_pending', models.JSONField(blank=True, default=list)),
                ('missing_customer_info', models.JSONField(blank=True, default=list)),
                ('probable_duplicates', models.JSONField(blank=True, default=list)),
                ('sla_risks', models.JSONField(blank=True, default=list)),
                ('high_effort_accounts', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_snapshots', to='ai.airun')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_queue_snapshots', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'created_at'], name='ai_queueint_workspa_0b8c15_idx')],
            },
        ),
    ]
