# Generated by Django 6.0.5 on 2026-05-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_aiprovidersettings_queue_intelligence_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovidersettings',
            name='generation_retention_days',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='monthly_run_cap',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='monthly_token_cap',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
