# Generated by Django 6.0.5 on 2026-05-08 02:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('pending', 'Pending'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('source', models.CharField(choices=[('internal', 'Internal'), ('portal', 'Portal'), ('email', 'Email')], default='internal', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='crm.contact')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='crm.organization')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_tickets', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal')], default='public', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_comments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comments', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='ticket-attachments/')),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_attachments', to='workspaces.workspace')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticketcomment')),
            ],
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['workspace', 'status'], name='tickets_tic_workspa_9983da_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['workspace', 'assignee'], name='tickets_tic_workspa_c5e2aa_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['workspace', 'created_at'], name='tickets_tic_workspa_2124d1_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['workspace', 'organization'], name='tickets_tic_workspa_828961_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['workspace', 'contact'], name='tickets_tic_workspa_e16a94_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcomment',
            index=models.Index(fields=['workspace', 'ticket', 'visibility'], name='tickets_tic_workspa_43a6de_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcomment',
            index=models.Index(fields=['workspace', 'created_at'], name='tickets_tic_workspa_3a7df0_idx'),
        ),
    ]
