# Generated by Django 6.0.5 on 2026-05-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcomment',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal')], default='internal', max_length=20),
        ),
    ]
