# Generated by Django 6.0.5 on 2026-05-08 04:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_organization_account_owner_organization_address_and_more'),
        ('tickets', '0002_alter_ticketcomment_visibility'),
        ('workspaces', '0002_workspace_first_response_target_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='first_response_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='next_response_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='waiting_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['workspace', 'first_response_due_at'], name='tickets_tic_workspa_5bec65_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['workspace', 'next_response_due_at'], name='tickets_tic_workspa_8277bd_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['workspace', 'waiting_since'], name='tickets_tic_workspa_7e0e14_idx'),
        ),
    ]
