# Generated by Django 6.0.5 on 2026-05-08 05:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_first_response_due_at_and_more'),
        ('workspaces', '0003_businesshourscalendar_invitation_slapolicy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTicketFilter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('query', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TicketRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('related', 'Related'), ('duplicate', 'Duplicate'), ('merged', 'Merged')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ticketattachment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='ticketattachment',
            name='is_public',
        ),
        migrations.AddField(
            model_name='ticket',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_sources', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='content_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='customer_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='size_bytes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='ticketattachment',
            index=models.Index(fields=['workspace', 'ticket', 'customer_visible'], name='tickets_tic_workspa_6693ae_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketattachment',
            index=models.Index(fields=['workspace', 'created_at'], name='tickets_tic_workspa_f70c86_idx'),
        ),
        migrations.AddField(
            model_name='savedticketfilter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_ticket_filters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedticketfilter',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_ticket_filters', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='ticketrelation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketrelation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticketrelation',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticketrelation',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_relations', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='savedticketfilter',
            index=models.Index(fields=['workspace', 'user'], name='tickets_sav_workspa_ef7440_idx'),
        ),
        migrations.AddIndex(
            model_name='savedticketfilter',
            index=models.Index(fields=['workspace', 'is_default'], name='tickets_sav_workspa_ffb777_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedticketfilter',
            unique_together={('workspace', 'user', 'name')},
        ),
        migrations.AddIndex(
            model_name='ticketrelation',
            index=models.Index(fields=['workspace', 'relation_type'], name='tickets_tic_workspa_364949_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketrelation',
            index=models.Index(fields=['workspace', 'source'], name='tickets_tic_workspa_b07138_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketrelation',
            index=models.Index(fields=['workspace', 'target'], name='tickets_tic_workspa_1151a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketrelation',
            unique_together={('workspace', 'source', 'target', 'relation_type')},
        ),
    ]
